### ISSUE TITLE
Extrair anexos das respostas

### ISSUE THREAD

**Issue by andresmrm** [okfn-brasil/esiclivre#1]
Aparentemente podem vir mais de um anexo por resposta. Precisamos de uma resposta com anexo para descobrir como pegá-lo, seja por e-mail ou por interface do site.

**Comment by alexandre** [comment]
@andresmrm,

Mas o anexo não fica na mensagem, ele tem uma area especifica. Basicamente (AFAIK) o anexo pertence ao pedido e, pelos pedidos com mais de um anexo, até agora não tivemos problemas com isso.

Teve algum erro ou o processo mudou mesmo?

[ ]'s

**Comment by andresmrm** [comment]
Não, é só uma issue antiga e desatualizada mesmo. =P
