### ISSUE TITLE
joinedload

### ISSUE THREAD

**Issue by alexandre** [okfn-brasil/esiclivre#6]
Nós realmente precisamos disso? Eu não consegui entender o uso.

**Comment by andresmrm** [comment]
Você diz as linhas como:

```
        pedido = (db.session.query(Pedido)
                  .options(joinedload('history'))
                  .options(joinedload('keywords'))
                  .filter_by(protocol=protocolo).one())
```

Até onde entendi isso já carrega `history` e `keywords` do `Pedido` filtrado, em uma única query. Caso contrário seriam 3 nesse caso.
Ou entendi errado?
http://docs.sqlalchemy.org/en/latest/orm/loading_relationships.html

**Comment by alexandre** [comment]
@andresmrm ,

Não, não entendeu. Fui eu mesmo. Eu havia disconsiderado o 1-N. Valeu
